---
title: Two By Two
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Two/Two
author: Shubhkirti Sharma
description: Two/Two is a flat dark theme for Jekyll Blogs
url: http://shubhkirtisharma.com
avatar: images/two-by-two.svg
email: shubhkirt.work@gmail.com
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: wowufoundme/two-by-two
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: __shubhkirti__
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
baseurl: ''
permalink: "/:title/"
source: "."
destination: "./_site"
version: v3.6.2
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
- coderay
